name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache West modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.ccache
            app/zephyr
            app/modules
            app/nrfxlib
          key: ${{ runner.os }}-zmk-build

      - name: Setup Zephyr ecosystem
        uses: zephyrproject-rtos/action-zephyr-setup@v1

      - name: Build Firmware
        uses: zmkfirmware/zmk-build-action@v2
        with:
          board: nice_nano_v2
          shield: teclado
